### ISSUE TITLE
missing field `cargo_args`

### ISSUE THREAD

**Issue by hasali19** [dnaka91/llvm-cov-pretty#8]
### Describe the bug

I'm getting the error below when running this command:

```
cargo llvm-cov --features mocks --json | llvm-cov-pretty
```

```
Error: 
   0: failed parsing report data from STDIN
   1: missing field `cargo_args` at line 1 column 44038817

Note: JSON path: cargo_llvm_cov
```

### Expected behavior

Report should be generated without any errors

### What operating system are you using?

Linux

### Additional context

llvm-cov-pretty 0.1.8
cargo-llvm-cov 0.5.33

**Comment by taiki-e** [comment]
`CargoLlvmCov` struct has `version`, `manifest_path`, `cargo_args`, and `test_args` fields, but cargo-llvm-cov actually has only `version` and `manifest_path` fields. (https://github.com/taiki-e/cargo-llvm-cov/commit/1ea8be492344ab09e9ae5bb7fd24f69135d99a0c)
https://github.com/dnaka91/llvm-cov-pretty/blob/f9515420bfc3b8894e0d8fee430e28ea56d260bc/src/schema.rs#L292-L303

**Comment by dnaka91** [comment]
Sorry, I was experimenting with those fields when I added this feature to `cargo-llvm-cov` and forgot to remove them later on. Still worked for me because of a custom build that took precedence over the global installation.

I removed those fields in the latest `v1.0.9`, should work now.
